### ISSUE TITLE
about increasing the number of agent and obstacle

### ISSUE THREAD

**Issue by Mohammed22668** [nicofretti/MAPF#1]
Dear author, i hope you are doing well. I'm just wondering about how to increase the number of obstacles and agents in the environment.

**Comment by nicofretti** [comment]
Hi, you must manually set them in the file `run_experiments.py`:
```python
  # line 98 for the `random mode` and 125 for the `success mode`
  map_size = 10;obstacles_dist = .05;max_agents=20
  ...
```
- `map_size` is the dimension of the grid
- `obstacles_dist` indicates the probability of each cell of being occupied
- `max_agents` the max number of agents to put in the grid
 
Thanks for your question, I appreciate it.

**Comment by Mohammed22668** [comment]
Thanks 🌹

في خميس، ١٦ حزيران، ٢٠٢٢ في ١١:٤٢ ص، كتب Frex ***@***.***>:

**Comment by Mohammed22668** [comment]
Hi again. I hope you are doing well.
I have another question about the environment, which is how can I change
the position of the obstacle. Also can i make the environment static that
means the random map will be static i.e (static map without any changes)
and change the position of the obstacles.
Thanks in advance
Best regards

في خميس، ١٦ حزيران، ٢٠٢٢ في ١١:٤٧ ص، كتب MOHAMMED AL-KHAFAJI <
***@***.***>:

**Comment by nicofretti** [comment]
Hi, you can actually make your own map by looking at the examples inside the folder `instances` like this example:
```python

# file instances/exp0.txt

4 7
@ @ @ @ @ @ @
@ . . . . . @
@ @ @ . @ @ @
@ @ @ @ @ @ @
2
1 1 1 5
1 2 1 4
```
Where you have to write:
- Height and width of the map
- Draw the map (`@` indicates the obstacle)
- Specify the number of agents
- For every agent type the start position and the target (like the example (1,1) to (1,5) for the first agent)

After make your map you can simply run the command:
```bash
python run_experiments.py --instance PATH --solver CBS
```
Where in the `PATH` is the path of your file.
