### ISSUE TITLE
Task 1-3

### ISSUE THREAD

**Issue by MauritsUdB** [nicofretti/MAPF#2]
Hi Nico, I was reading through the description at the beginning and you talked about using the repository of [jzagoli](https://github.com/jzagoli) for the first three steps. When clicking on the link I does not find a page, I was wondering if you have the link to the repository or the code for the first three steps. ## Edit ## I found it!

**Comment by nicofretti** [comment]
Hi Maurtis, thank you he changed his name on github, I have to update it rn!

**Comment by MauritsUdB** [comment]
Hi Nico, do you maybe have some tips on how to combine prioritized planning with some kind of vision? Or something in the realm of decentralized approach where agents operate independently with local information and make their own decisions about pathfinding while occasionally communicating with other agents to avoid conflicts.

**Comment by nicofretti** [comment]
Hi Maurtis, maybe this paper can be useful to you [DMAPF](https://arxiv.org/pdf/2109.08288.pdf)
